name: test
on: [push, pull_request]
jobs:
  build:
    name: Build, Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 12.x
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Install, lint:hbs, lint:js, tests
      run: |
        npm install
        npm run lint:js
        npm test

  additional:
    name: Ember additional ${{matrix.ember-release}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ember-release:
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default-with-jquery
          - ember-classic

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 12.x
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Install, lint:js, tests
      continue-on-error: true
      run: |
        npm install
        node_modules/.bin/ember try:one ${{matrix.ember-release}}
